### ISSUE TITLE
Build and export is still not working on MacOS

### ISSUE THREAD

**Issue by wildraid** [exasol/script-languages#12]
1) Argument parsing is not working (--flavor, --target).
2) mktemp fails
```
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

**Comment by stmandl** [comment]
Hi Vitaly, can you please check if it works for you now?
I've added "short flags" versions of the build scripts that should also work on Mac OS X (`./build -f mini`) and changed the calls to `mktemp`.
I wasn't able to check if `test_complete` works though, because my Mac at home is too old for it.

**Comment by wildraid** [comment]
@stmandl , perfect!
I'll check this on weekend. I have a plenty of Mac's  :)

**Comment by stmandl** [comment]
Thx, the problem now was determining the number of cores via /proc/cpuinfo, which does not exist on MacOS X. Please try again.
We have no automated tests for Mac.

**Comment by stmandl** [comment]
I just learned the hard way that travis does not support docker on mac os x. So there probably will be no automated tests until they do.

**Comment by wildraid** [comment]
@stmandl , yes, it works :)

Steps `build`, `export` are ok.

`test` phases for flavor "mini" fails with following error:
```
Badoos-MacBook-Pro-248:scriptlang vitalymarkov$ ./test -f mini
111 = -f
111 = --
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.8M  100 11.8M    0     0  2665k      0  0:00:04  0:00:04 --:--:-- 2824k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  390k  100  390k    0     0  1297k      0 --:--:-- --:--:-- --:--:-- 1297k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.9M  100 18.9M    0     0  3594k      0  0:00:05  0:00:05 --:--:-- 3533k
Requirement already satisfied: pyodbc in /Users/vitalymarkov/anaconda3/lib/python3.6/site-packages (from -r ./tests/requirements.txt (line 1))
Requirement already satisfied: pytz in /Users/vitalymarkov/anaconda3/lib/python3.6/site-packages (from -r ./tests/requirements.txt (line 2))
Requirement already satisfied: lxml in /Users/vitalymarkov/anaconda3/lib/python3.6/site-packages (from -r ./tests/requirements.txt (line 3))
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
./test: line 82: typeset: -A: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
```

Thanks for you help. I think, sole Mac users will appreciate it.

**Comment by wildraid** [comment]
By the way, you also write control scripts in Python. It will be uniform across all platforms and easier to understand.

Python 3.6+ is better if you have a choice.

**Comment by stmandl** [comment]
@wildraid thanks,
Strangely, on travis the only language supported on Mac OS seems to be GO, not even Python.
Probably we should use GO ;-)
Btw, you should use `test_complete` instead of `test` (see `.travis.yml`), but still it will not work on Mac OS :-(

**Comment by stmandl** [comment]
@wildraid 
as Travis does not do it for me and my old Mac at home is ... well, too old.
Could you please manually check on one of your Macs, if the tests work:
`./test_complete --flavor=mini --test-folder=mini --generic-test-lang=mini`

**Comment by stmandl** [comment]
Sorry, yes of course you need the short options on Mac:
```bash
./test_complete -f mini -t mini -g mini
```

**Comment by wildraid** [comment]
@stmandl , ok, it works up until certain moment.

```
ALTER SESSION SET SCRIPT_LANGUAGES='MYPYTHON=localzmq+protobuf:///bucketfsname/bucketname/mini?lang=python#buckets/bucketfsname/bucketname/mini/exaudf/exaudfclient';
+ ./clean
Removing all exited containers:
Removing all created containers:
Removing all running containers:
Removing dangling images: 633f74434b21 117e5bfeeb1e
Deleted: sha256:633f74434b21589e6731b911cb79802c3cc30f896cf51d6b3aa84d68d87bc6fd
Deleted: sha256:18df3c8a05980015861ad28d7f02abe94972effd8122f4807f38ad30a0f595e7
Deleted: sha256:b8313ffe3b1acd2e929b2bf7c70c6ad95eead7234fe39977072fa4c1a67b0855
Deleted: sha256:117e5bfeeb1ef9eb381053c5c913bf01e38821dfd9399ce721b759af8a7bc876
Deleted: sha256:0973a3f08de74ccded3b8a3bac1d5f80134bcec67292fd9e6207fccfb05151f0
Deleted: sha256:3a44a343abfdf71a44c27f4c0275171b106b83e54e1b9a19b6b1ca3718dd154f
+ ./start_dockerdb -p 8903 -b 6598
config files dir for exadb: /tmp/udftestdb
1+0 records in
1+0 records out
1 bytes transferred in 0.000026 secs (38480 bytes/sec)
Unable to find image 'exasol/docker-db:6.0.12-d1' locally
6.0.12-d1: Pulling from exasol/docker-db
b268bb2f98b2: Pull complete 
326d71fa779c: Pull complete 
d2a9f8715db2: Pull complete 
e893568f4862: Pull complete 
Digest: sha256:4d5d69b15c25f38fc7673ab82e4da7613c82201fbcdff02d723718db584fec29
Status: Downloaded newer image for exasol/docker-db:6.0.12-d1
e667da92514ac424f43f2678bafa97ae2b6286d15aba7fe139a63a716d831be0
Wait until database is ready...
 [2018-12-21 10:06:26] exadt:: '/exa/etc' already exists! Doing partial initialization.
 [2018-12-21 10:06:26] exadt:: searching for the first interface with state UP
 [2018-12-21 10:06:26] exadt:: copying license file '/.license.xml' to '/exa/etc'
 [2018-12-21 10:06:26] exadt:: changing DB, volume and BucketFS owner to 500 : 500
 [2018-12-21 10:06:26] exadt:: setting hostname to 'n11'
 [2018-12-21 10:06:26] exadt:: calling '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/exainit.py'
 [2018-12-21 10:06:27] stage0: Run stage 'stage0'
 [2018-12-21 10:06:27] stage0: Run service environment_conf
 [2018-12-21 10:06:27] stage0: Run service license_check
 [2018-12-21 10:06:27] stage0: Run service prepare_update
 [2018-12-21 10:06:27] stage0: Run service next_stage
 [2018-12-21 10:06:27] stage0: Current environment settings:
 [2018-12-21 10:06:27] stage0: >>> [('COS_CONF_DIR', '/exa'),
 [2018-12-21 10:06:27] stage0: >>>  ('COS_DIRECTORY', '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12'),
 [2018-12-21 10:06:27] stage0: >>>  ('EXA_DB_VERSION', '6.0.12'),
 [2018-12-21 10:06:27] stage0: >>>  ('EXA_IMG_VERSION', '6.0.12-d1'),
 [2018-12-21 10:06:27] stage0: >>>  ('EXA_NODE_ID', '11'),
 [2018-12-21 10:06:27] stage0: >>>  ('EXA_OS_VERSION', '6.0.12'),
 [2018-12-21 10:06:27] stage0: >>>  ('EXA_RE_VERSION', '6.0.12'),
 [2018-12-21 10:06:27] stage0: >>>  ('HOME', '/'),
 [2018-12-21 10:06:27] stage0: >>>  ('HOSTNAME', 'n11'),
 [2018-12-21 10:06:27] stage0: >>>  ('LANG', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_ADDRESS', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_COLLATE', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_CTYPE', 'en_US.utf8'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_IDENTIFICATION', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_MEASUREMENT', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_MESSAGES', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_MONETARY', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_NAME', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_NUMERIC', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_PAPER', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_TELEPHONE', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('LC_TIME', 'C'),
 [2018-12-21 10:06:27] stage0: >>>  ('MANPATH',
 [2018-12-21 10:06:27] stage0: >>>   '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/man:/usr/local/share/man:/usr/share/man'),
 [2018-12-21 10:06:27] stage0: >>>  ('PATH',
 [2018-12-21 10:06:27] stage0: >>>   '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/bin:/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/sbin:/usr/opt/EXASuite-6/EXARuntime-6.0.12/bin:/usr/opt/EXASuite-6/EXARuntime-6.0.12/sbin:/bin:/sbin:/usr/bin:/usr/sbin'),
 [2018-12-21 10:06:27] stage0: >>>  ('RE_PATH', '/usr/opt/EXASuite-6/EXARuntime-6.0.12')]
 [2018-12-21 10:06:27] stage0: You have following license limits:
 [2018-12-21 10:06:27] stage0: >>>     Database memory (GiB):        200 Main memory (RAM) usable by databases
 [2018-12-21 10:06:27] stage0: >>>             Cluster nodes:          1 Number of usable cluster nodes
 [2018-12-21 10:06:27] stage0: >>>   Database raw size (GiB):  unlimited Raw Size of Databases (see Value RAW_OBJECT_SIZE in System Tables)
 [2018-12-21 10:06:27] stage0: >>>   Database mem size (GiB):  unlimited Compressed Size of Databases (see Value MEM_OBJECT_SIZE in System Tables)
 [2018-12-21 10:06:27] stage0: >>>           Expiration date:  unlimited Date of license expiration
 [2018-12-21 10:06:27] stage0: Next stage will be 'stage1'.
 [2018-12-21 10:06:28] stage1: Run stage 'stage1'
 [2018-12-21 10:06:28] stage1: Run service node_options
 [2018-12-21 10:06:28] stage1: Run service prepare_update
 [2018-12-21 10:06:28] stage1: Run service create_users
 [2018-12-21 10:06:28] stage1: Run service node_etc_cos
 [2018-12-21 10:06:28] stage1: Run service name_resolution
 [2018-12-21 10:06:28] stage1: Run service sysctl
 [2018-12-21 10:06:28] stage1: Run service diskconf
 [2018-12-21 10:06:28] stage1: Run service broadcast_peers
 [2018-12-21 10:06:28] stage1: Run service root_bashrc
 [2018-12-21 10:06:28] stage1: Run service super_cored
 [2018-12-21 10:06:28] stage1: Run service cored_command
 [2018-12-21 10:06:28] stage1: Run service next_stage
 [2018-12-21 10:06:28] stage1: Current node id is '11'
 [2018-12-21 10:06:28] stage1: Current node options are:
 [2018-12-21 10:06:28] stage1: >>> [('disks',
 [2018-12-21 10:06:28] stage1: >>>   <config at 0x7f7792a4dd08: [('default', <config at 0x7f7792a4de30: [('name', 'default'), ('devices', [('dev.1.data', 'dev.1.meta')]), ('mapping', [('dev.1', '/exa/data/storage')]), ('mapped_devices', [('/exa/data/storage/dev.1.meta', '/exa/data/storage/dev.1.meta'), ('/exa/data/storage/dev.1.data', '/exa/data/storage/dev.1.data')]), ('direct_io', True)]>)]>),
 [2018-12-21 10:06:28] stage1: >>>  ('docker_volume', '/exa/etc/n11'),
 [2018-12-21 10:06:28] stage1: >>>  ('exposed_ports', [(8888, 8899), (6583, 6594)]),
 [2018-12-21 10:06:28] stage1: >>>  ('id', '11'),
 [2018-12-21 10:06:28] stage1: >>>  ('name', 'n11'),
 [2018-12-21 10:06:28] stage1: >>>  ('private_ip', '172.17.0.2'),
 [2018-12-21 10:06:28] stage1: >>>  ('private_net', '172.17.0.2/16'),
 [2018-12-21 10:06:28] stage1: >>>  ('uuid', '5D11CDFCDEA74475833F1892426428873D4BEB66')]
 [2018-12-21 10:06:28] stage1: Following users where created: 500:500
 [2018-12-21 10:06:28] stage1: Current node UUID is '5D11CDFCDEA74475833F1892426428873D4BEB66' (EXAConf)
 [2018-12-21 10:06:28] stage1: /etc/hosts content:
 [2018-12-21 10:06:28] stage1: >>> # hosts is generated by exainit
 [2018-12-21 10:06:28] stage1: >>> 127.0.0.1 localhost localhost.localdomain
 [2018-12-21 10:06:28] stage1: >>> 172.17.0.2 n11
 [2018-12-21 10:06:28] stage1: /etc/resolv.conf content:
 [2018-12-21 10:06:28] stage1: >>> # Generated by exainit
 [2018-12-21 10:06:28] stage1: Following sysctl parameters have incorrect values:
 [2018-12-21 10:06:28] stage1:                    net.core.rmem_default: '4194304' != None
 [2018-12-21 10:06:28] stage1:                    net.core.wmem_default: '524288' != None
 [2018-12-21 10:06:28] stage1:                        net.ipv4.tcp_rmem: '4096        87380   1048576' != None
 [2018-12-21 10:06:28] stage1:                        net.core.rmem_max: '4194304' != None
 [2018-12-21 10:06:28] stage1:                       kernel.threads-max: '274432' != '15989'
 [2018-12-21 10:06:28] stage1:                        net.ipv4.tcp_wmem: '4096        16384   4194304' != None
 [2018-12-21 10:06:28] stage1:                        net.core.wmem_max: '1048576' != None
 [2018-12-21 10:06:28] stage1:              net.core.netdev_max_backlog: '1000' != None
 [2018-12-21 10:06:28] stage1: Register '/exa/data/storage/dev.1.data' device in meta device '/exa/data/storage/dev.1.meta'
 [2018-12-21 10:06:28] stage1: Following nodes are registered: 172.17.0.2:10001
 [2018-12-21 10:06:28] stage1: super_cored started with return code: 0
 [2018-12-21 10:06:28] stage1: Call cored with following command: '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/cos_cored -n 11 --renice -10 --auth-sock-dir /var/lock --oom-adjustment -5 -m 224.0.0.1 -s 172.17.0.2 -t 10001 -l /exa/logs/cored --default-file-mode 644 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/exainit.py stage2 /proc/1/fd/2'
 [2018-12-21 10:06:28] stage1: Next stage will be 'stage2'.
 [2018-12-21 10:06:28] Starting with PID 1
 [2018-12-21 10:06:28] Core Daemon v6.0.12  (build 14860)
 [2018-12-21 10:06:28] Using multicast address 224.0.0.1.
 [2018-12-21 10:06:28] Receive socket is bind to interface eth0.
 [2018-12-21 10:06:28] Started UNIX socket authentication engine (authentication socket directory is /var/lock).
 [2018-12-21 10:06:28] Core Engine started ... logdir=/exa/logs/cored 
 [2018-12-21 10:06:28] Received transitional Config Change Message: rid=0 seq=176094248965 conf=3 <>
 [2018-12-21 10:06:28] Received regular Config Change Message: rid=4 seq=0 conf=3 < ip://n11:10001>
 [2018-12-21 10:06:28] Self information: NID = <invalid>, address = <none>; event_id: 0; no. of cluster nodes: 0
 [2018-12-21 10:06:28]   11: ip://n11:10001 (offline) usage: 0
 [2018-12-21 10:06:28] No partitions known.
 [2018-12-21 10:06:42] Active Nodes: 1 - ip://n11:10001 
 [2018-12-21 10:06:42] Nodes of last Configuration: 0 - 
 [2018-12-21 10:06:53] Config Change completed.
 [2018-12-21 10:06:53] Self information: NID = 11, address = ip://n11:10001; event_id: 2; no. of cluster nodes: 1
 [2018-12-21 10:06:53]   11: ip://n11:10001 (available) usage: 0
 [2018-12-21 10:06:53] No partitions known.
 [2018-12-21 10:06:54] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/exainit.py with PID:45 UID:0 GID:0 Part:0 Node:11
 [2018-12-21 10:06:54] stage2: Run stage 'stage2'
 [2018-12-21 10:06:54] stage2: Run service node_options
 [2018-12-21 10:06:54] stage2: Run service prepare_update
 [2018-12-21 10:06:54] stage2: Run service wait_for_nodes
 [2018-12-21 10:06:54] stage2: Run service next_stage_for_slave
 Waiting for 0 slave nodes to reach the barrier (13000)
 [2018-12-21 10:06:54] stage2: Run service sshd
 [2018-12-21 10:06:54] Started /bin/sh with PID:55 UID:0 GID:0 Part:1 Node:0
 [2018-12-21 10:06:55] child 55 (Part:1 Node:0 sh) returned with state 0.
 [2018-12-21 10:06:56] Started /bin/sh with PID:91 UID:0 GID:0 Part:2 Node:0
 [2018-12-21 10:06:57] child 91 (Part:2 Node:0 sh) returned with state 0.
 Fri Dec 21 10:06:57 UTC 2018: start script '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/sbin/cos_sync_files'.
 Fri Dec 21 10:06:57 UTC 2018: pack files for sync.
 root/.ssh/id_rsa
 root/.ssh/id_rsa.pub
 root/.ssh/authorized_keys
 etc/ssh/ssh_config
 No nodes to synchronize.
 Fri Dec 21 10:06:57 UTC 2018: start script '/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/sbin/cos_sync_files'.
 Fri Dec 21 10:06:57 UTC 2018: pack files for sync.
 u00500/.ssh/id_rsa
 u00500/.ssh/id_rsa.pub
 u00500/.ssh/authorized_keys
 etc/ssh/ssh_config
 No nodes to synchronize.
 [2018-12-21 10:06:58] Started /usr/sbin/sshd with PID:178 UID:0 GID:0 Part:3 Node:0
 [2018-12-21 10:06:58] stage2: Run service merge_and_sync_exaconf
 FILE_SYNC: Starting partition with shell and command 'scp /exa/etc/EXAConf "n11:/exa/spool/sync/EXAConf_irBm5w/EXAConf_$EXA_NODE_ID" 2>&1' on all nodes.
 [2018-12-21 10:06:58] Started /bin/sh with PID:179 UID:0 GID:0 Part:4 Node:0
 [2018-12-21 10:06:59] child 179 (Part:4 Node:0 sh) returned with state 0.
 FILE_SYNC: Synchronizing file '/exa/etc/EXAConf' between all nodes.
 FILE_SYNC: Generated temporary filename '/exa/etc/EXAConf_0.11.1545386819.39'.
 FILE_SYNC: Starting partition with shell and command 'tee /exa/etc/EXAConf_0.11.1545386819.39 2>&1 1>/dev/null' on all nodes.
 [2018-12-21 10:06:59] Started /bin/sh with PID:189 UID:0 GID:0 Part:5 Node:0
 FILE_SYNC: 'tee' wrote 4396 bytes.
 [2018-12-21 10:07:00] child 189 (Part:5 Node:0 sh) returned with state 0.
 FILE_SYNC: Transferring access rights of file '/exa/etc/EXAConf' to file '/exa/etc/EXAConf_0.11.1545386819.39' .
 FILE_SYNC: Starting partition with shell and command 'if [ -e /exa/etc/EXAConf ]; then chmod --reference=/exa/etc/EXAConf /exa/etc/EXAConf_0.11.1545386819.39 && chown --reference=/exa/etc/EXAConf /exa/etc/EXAConf_0.11.1545386819.39; fi 2>&1' on all nodes.
 [2018-12-21 10:07:00] Started /bin/sh with PID:191 UID:0 GID:0 Part:6 Node:0
 [2018-12-21 10:07:01] child 191 (Part:6 Node:0 sh) returned with state 0.
 FILE_SYNC: Moving file '/exa/etc/EXAConf_0.11.1545386819.39' to '/exa/etc/EXAConf'.
 FILE_SYNC: Starting partition with shell and command 'mv -f /exa/etc/EXAConf_0.11.1545386819.39 /exa/etc/EXAConf 2>&1' on all nodes.
 [2018-12-21 10:07:02] Started /bin/sh with PID:194 UID:0 GID:0 Part:7 Node:0
 [2018-12-21 10:07:03] child 194 (Part:7 Node:0 sh) returned with state 0.
 [2018-12-21 10:07:03] stage2: Run service slave_unblock
 [2018-12-21 10:07:03] stage2: Run service next_stage
 [2018-12-21 10:07:03] stage2: Current node id is '11'
 [2018-12-21 10:07:03] stage2: All nodes are online: ('n11',)
 [2018-12-21 10:07:03] stage2: Current node is a master node.
 [2018-12-21 10:07:03] stage2: Next stage will be 'stage3'.
 [2018-12-21 10:07:03] stage2: sshd was started with PID 3
 [2018-12-21 10:07:03] stage2: SSH keys for following users was generated: 0, 500
 [2018-12-21 10:07:03] stage2: Merged the EXAConf of 1 nodes.
 [2018-12-21 10:07:03] stage2: Next stage will be 'stage3'.
 [2018-12-21 10:07:03] stage3: Run stage 'stage3'
 [2018-12-21 10:07:03] stage3: Run service node_options
 [2018-12-21 10:07:03] stage3: Run service prepare_update
 [2018-12-21 10:07:03] stage3: Run service storaged_conf
 [2018-12-21 10:07:03] stage3: Run service databases_conf
 [2018-12-21 10:07:03] stage3: Run service wait_for_nodes
 [2018-12-21 10:07:03] stage3: Run service bucketfs
 [2018-12-21 10:07:03] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/bucketfsd with PID:205 UID:0 GID:0 Part:8 Node:0
 [2018-12-21 10:07:03] stage3: Run service storaged_conf
 [2018-12-21 10:07:03] stage3: Run service next_stage_for_slave
 Waiting for 0 slave nodes to reach the barrier (13001)
 [2018-12-21 10:07:03] stage3: Run service logd
 [2018-12-21 10:07:04] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/logd with PID:206 UID:0 GID:0 Part:9 Node:0
 [2018-12-21 10:07:04] stage3: Run service lockd
 [2018-12-21 10:07:04] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/lockd with PID:207 UID:0 GID:0 Part:10 Node:0
 [2018-12-21 10:07:04] stage3: Run service dwad
 [2018-12-21 10:07:04] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/dwad with PID:210 UID:0 GID:0 Part:11 Node:0
 [2018-12-21 10:07:05] stage3: Run service storaged
 [2018-12-21 10:07:06] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/bin/csctrl with PID:252 UID:0 GID:0 Part:12 Node:0
 [2018-12-21 10:07:06] Started /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/cos_storage with PID:259 UID:0 GID:0 Part:13 Node:0
 [2018-12-21 10:07:06] child 252 (Part:12 Node:0 csctrl) returned with state 0.
 [2018-12-21 10:07:06] Force new cluster synchronization upon user request from partition 13.
 [2018-12-21 10:07:06] Force new cluster configuration upon user request on node n11.
 [2018-12-21 10:07:06] Received transitional Config Change Message: rid=4 seq=62 conf=7 < ip://n11:10001>
 [2018-12-21 10:07:06] Received regular Config Change Message: rid=8 seq=0 conf=7 < ip://n11:10001>
 [2018-12-21 10:07:06] Self information: NID = 11, address = ip://n11:10001; event_id: 39; no. of cluster nodes: 1
 [2018-12-21 10:07:06]   11: ip://n11:10001 (available) usage: 6
 [2018-12-21 10:07:06]   Partition 3 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 8 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 9 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 10 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 11 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 13 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06] Registered local processes:
 [2018-12-21 10:07:06] PID: 45 (PID: 0, NID: 11)
 [2018-12-21 10:07:06] PID: 178 (PID: 3, NID: 0)
 [2018-12-21 10:07:06] PID: 205 (PID: 8, NID: 0)
 [2018-12-21 10:07:06] PID: 206 (PID: 9, NID: 0)
 [2018-12-21 10:07:06] PID: 207 (PID: 10, NID: 0)
 [2018-12-21 10:07:06] PID: 210 (PID: 11, NID: 0)
 [2018-12-21 10:07:06] PID: 259 (PID: 13, NID: 0)
 [2018-12-21 10:07:06] Active Nodes: 1 - ip://n11:10001 
 [2018-12-21 10:07:06] Nodes of last Configuration: 1 - ip://n11:10001 
 [2018-12-21 10:07:06] Config Change completed.
 [2018-12-21 10:07:06] Self information: NID = 11, address = ip://n11:10001; event_id: 47; no. of cluster nodes: 1
 [2018-12-21 10:07:06]   11: ip://n11:10001 (available) usage: 6
 [2018-12-21 10:07:06]   Partition 3 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 8 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 9 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 10 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 11 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06]   Partition 13 contains 1 nodes: [ 11 ]
 [2018-12-21 10:07:06] Registered local processes:
 [2018-12-21 10:07:06] PID: 45 (PID: 0, NID: 11)
 [2018-12-21 10:07:06] PID: 178 (PID: 3, NID: 0)
 [2018-12-21 10:07:06] PID: 205 (PID: 8, NID: 0)
 [2018-12-21 10:07:06] PID: 206 (PID: 9, NID: 0)
 [2018-12-21 10:07:06] PID: 207 (PID: 10, NID: 0)
 [2018-12-21 10:07:06] PID: 210 (PID: 11, NID: 0)
 [2018-12-21 10:07:06] PID: 259 (PID: 13, NID: 0)
 [2018-12-21 10:07:09] child 259 (Part:13 Node:0 cos_storage) terminated with signal 6. 
 [2018-12-21 10:07:09] IF_IEVH::INFO: Local storage service process exited! Switching to network communication mode...
 [2018-12-21 10:07:09] IF::ERROR: Request of type <add_hdd> failed with result: e_dest_unreachable!
 [2018-12-21 10:07:09] IF:: In file 'cosif_storage.cc', line 2634 ('do_request()').
 [2018-12-21 10:07:09] Timeout occured for: 'r = client_channel::reconnect()'!
 [2018-12-21 10:07:09] Timeout occured for: 'r = client_channel::reconnect()'!
 [2018-12-21 10:07:09] Timeout occured for: 'r = client_channel::reconnect()'!
 [2018-12-21 10:07:09] Timeout occured for: 'r = client_channel::reconnect()'!
 [2018-12-21 10:07:09] Timeout occured for: 'r = client_channel::reconnect()'!
 [2018-12-21 10:07:09] Timeout occured for: 'r = client_channel::reconnect()'!
 [2018-12-21 10:07:09] IF::ERROR: Reconnecting the client channel failed with result: e_dest_unreachable!
 [2018-12-21 10:07:09] IF:: In file 'cosif_storage.cc', line 709 ('reconnect()').
 
 backtracedecode <<EOBT
 Traceback (most recent call last):
   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/exainit.py", line 79, in <module>
     main(sys.argv)
   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/exainit.py", line 71, in main
     run(args[1])
   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/libexec/exainit.py", line 45, in run
     serv.run_result = serv.run()
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCOS.so(_ZN3COS9exceptionC1ERKS0_+0x75) [0x7f48a534d8f5]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCOS.so(_ZN3COS14client_channel9reconnectEv+0x2c8) [0x7f48a52c6ee8]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCosStorage.so(_ZN3COS7storage13cosif_storage9reconnectEv+0x5b) [0x7f48a3994eeb]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCosStorage.so(_ZN3COS7storage13cosif_storage23refresh_service_addressEv+0x10) [0x7f48a3995060]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCosStorage.so(_ZN3COS7storage16if_event_handler20handle_local_ss_stopEv+0x1a2) [0x7f48a39e09b2]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCosStorage.so(_ZN3COS7storage16if_event_handler11handleEventENS_4srefINS_5eventENS_12serializableEEE+0x1197) [0x7f48a39e2fa7]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCOS.so(_ZN3COS13event_channel7receiveclEv+0xf85) [0x7f48a52d2515]
 /usr/opt/EXASuite-6/EXAClusterOS-6.0.12/lib/libCOS.so(_ZN3COS6thread7executeEPv+0xe5) [0x7f48a53b2575]
 /usr/opt/EXASuite-6/EXARuntime-6.0.12/lib/libpthread.so.0(+0x7454) [0x7f48abc90454]
 /usr/opt/EXASuite-6/EXARuntime-6.0.12/lib/libc.so.6(clone+0x5f) [0x7f48ab2c549f]
 EOBT
   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/exainit/tasks/storage.py", line 105, in run
     direct_io=diskinfo.direct_io)  
   File "services/storage/interface/libCS_interface_py.pxi", line 502, in libCS_py.storage.add_hdd (.build/services/storage/interface/libCS_py.cc:7663)
 Exception: Failed to add HDD: communication error
 [2018-12-21 10:07:10] root child 45 (exainit.py) returned with state 1.
 [2018-12-21 10:36:29] -- MARK --
 [2018-12-21 10:51:29] -- MARK --
 [2018-12-21 11:06:29] -- MARK --
```

And it does not proceed after that.

**Comment by stmandl** [comment]
I'm closing this issue as the building and exporting part seem to work now.
