### ISSUE TITLE
Build of flavor -error

### ISSUE THREAD

**Issue by skarangi** [exasol/script-languages#41]
Hi,

I am getting this error while trying to build. Please help

INFO: [pid 2910] Worker Worker(salt=417001433, workers=5, host=data_science, username=skarangi, pid=2797) running   DockerCreateImageTask(image_name=exasol/script-language-container:python3-ds-EXASOL-6.1.0-build_deps)
INFO: [pid 2909] Worker Worker(salt=417001433, workers=5, host=data_science, username=skarangi, pid=2797) running   DockerCreateImageTask(image_name=exasol/script-language-container:python3-ds-EXASOL-6.1.0-udfclient_deps)
ERROR: [pid 2909] Worker Worker(salt=417001433, workers=5, host=data_science, username=skarangi, pid=2797) failed    DockerCreateImageTask(image_name=exasol/script-language-container:python3-ds-EXASOL-6.1.0-udfclient_deps)
Traceback (most recent call last):
  File "/home/skarangi/.local/share/virtualenvs/script-languages-30_bvrAI/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/skarangi/.local/share/virtualenvs/script-languages-30_bvrAI/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/skarangi/.local/share/virtualenvs/script-languages-30_bvrAI/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

**Comment by tkilias** [comment]
Hi @skarangi,

this looks like your user doesn't have the file system permission to access the socket of the docker daemon. Which OS do you use? Do you have root rights or sudo rights on this machine? This might help. Or can you ask the administrator to add your user to the docker group.

**Comment by tkilias** [comment]
Hi @skarangi,

were you able to solve your problem, or do you need more information? If it is solved, I would close this issue.
