### ISSUE TITLE
Error after upgrade of python-ds flavors to tensorflow >=1.14.0

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages#43]
After the upgrade to tensorflow 1.14.0 in the python3-ds flavors the following UDF fails:

> CREATE OR REPLACE python3 scalar SCRIPT tfbasic.import_keras() returns varchar(1000) as
> import keras
> import tensorflow
> import tensorflow_hub
> 
> def run(ctx):
>   return str(keras.__version__)+" "+str(tensorflow.__version__)
> /
> 
> SQL_EXA> select tfbasic.import_keras();

Error:

> EXA: select tfbasic.import_keras();
> Error: [22002] VM error: TypeError: Traceback (most recent call last):
>   File "IMPORT_KERAS", line 1, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/keras/__init__.py", line 3, in <module>
>     from . import utils
>   File "/usr/local/lib/python3.6/dist-packages/keras/utils/__init__.py", line 6, in <module>
>     from . import conv_utils
>   File "/usr/local/lib/python3.6/dist-packages/keras/utils/conv_utils.py", line 9, in <module>
>     from .. import backend as K
>   File "/usr/local/lib/python3.6/dist-packages/keras/backend/__init__.py", line 89, in <module>
>     from .tensorflow_backend import *
>   File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
>     import tensorflow as tf
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 729, in <module>
>     if _running_from_pip_package():
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 727, in _running_from_pip_package
>     _current_file_location.startswith(dir_) for dir_ in _site_packages_dirs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 727, in <genexpr>
>     _current_file_location.startswith(dir_) for dir_ in _site_packages_dirs)
> TypeError: startswith first arg must be str or a tuple of str, not NoneType
>  (Session: 1637316481507639556)

First thoughts:
- tensorflow checks where its files are located, probably here https://git.codingcafe.org/Mirrors/tensorflow/tensorflow/commit/5195204b47d1cf9516ff5eea8232fbff8d320521
- Not sure why, dir_ is None

Until a solution was found, we fix the version to 1.13.1

**Comment by tkilias** [comment]
This bug also affects Tensorflow 2.0.0. A bug report is to tensorflow is filed under:

**Comment by tkilias** [comment]
Should be solved with Tensorflow 2.3
